In [1]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

In [2]:
nnfs.init()

In [3]:
#Creating our Class

class Layer_Dense:
    #Initialize with random wights, and 0 bias
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))      
        
    # Forward pass
    def forward(self,inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [4]:
#Create a sample dataset
X, y = spiral_data(samples=100, classes=3)

In [5]:
#Create a dense_layer with 2 input features, and 3 output features
dense1 = Layer_Dense(2, 3)

In [6]:
#Put a forward pass through the layer
dense1.forward(X)

In [7]:
print(dense1.output[:5])

[[ 0.          0.          0.        ]
 [-0.00104752  0.00113954 -0.00047984]
 [-0.00274148  0.00317292 -0.00086922]
 [-0.00421884  0.00526663 -0.00055913]
 [-0.00577077  0.00714014 -0.0008943 ]]
