In [1]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

In [2]:
nnfs.init()

In [3]:
#Creating our Class

class Layer_Dense:
    #Initialize with random wights, and 0 bias
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))      
        
    # Forward pass
    def forward(self,inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [8]:
#Class for ReLu
class Activation_ReLU:
    def forward(self, inputs):        
        self.output = np.maximum(0, inputs)

#Class for softmax
class Activation_Softmax:
    
    #Forward Pass
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        sum_exp_values = np.sum(exp_values, axis=1, keepdims=True)
        self.output = exp_values / sum_exp_values

In [9]:
# Create dataset
X, y = spiral_data(samples=100, classes=3)


In [10]:
# Create Dense layer with 2 input features and 3 output values
dense1 = Layer_Dense(2, 3)


In [11]:
# Create ReLU activation (to be used with Dense layer):
activation1 = Activation_ReLU()


In [12]:
# Create second Dense layer with 3 input features (as we take output
# of previous layer here) and 3 output values (output values)
dense2 = Layer_Dense(3, 3)


In [13]:
# Create Softmax activation (to be used with Dense layer):
activation2 = Activation_Softmax()


In [14]:
# Make a forward pass of our training data through this layer
dense1.forward(X)


In [15]:
# Make a forward pass through activation function
# it takes the output of first dense layer here
activation1.forward(dense1.output)


In [16]:
# Make a forward pass through second Dense layer
# it takes outputs of activation function of first layer as inputs
dense2.forward(activation1.output)


In [17]:
# Make a forward pass through activation function
# it takes the output of second dense layer here
activation2.forward(dense2.output)

In [18]:
print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]]
